export type AdmissionRegion = "seoul" | "busan";

export type AdmissionDocument = {
  id: string;
  region: AdmissionRegion;
  regionLabel: string;
  university: string;
  file: string;
  downloadName: string;
};

export const admissionRegionFilters = [
  { id: "all", label: "전체" },
  { id: "seoul", label: "서울" },
  { id: "busan", label: "부산" },
] as const;

export type AdmissionRegionFilter = (typeof admissionRegionFilters)[number]["id"];

export const admissionDocuments: AdmissionDocument[] = [
  {
    id: "konkuk-univ",
    region: "seoul",
    regionLabel: "서울",
    university: "건국대",
    file: "/admissions/2028/seoul/konkuk-univ.pdf",
    downloadName: "건국대-2028-대입전형시행계획.pdf",
  },
  {
    id: "kyunghee-univ",
    region: "seoul",
    regionLabel: "서울",
    university: "경희대",
    file: "/admissions/2028/seoul/kyunghee-univ.pdf",
    downloadName: "경희대-2028-대입전형시행계획.pdf",
  },
  {
    id: "korea-univ",
    region: "seoul",
    regionLabel: "서울",
    university: "고려대",
    file: "/admissions/2028/seoul/korea-univ.pdf",
    downloadName: "고려대-2028-대입전형시행계획.pdf",
  },
  {
    id: "dongguk-univ",
    region: "seoul",
    regionLabel: "서울",
    university: "동국대",
    file: "/admissions/2028/seoul/dongguk-univ.pdf",
    downloadName: "동국대-2028-대입전형시행계획.pdf",
  },
  {
    id: "sogang-univ",
    region: "seoul",
    regionLabel: "서울",
    university: "서강대",
    file: "/admissions/2028/seoul/sogang-univ.pdf",
    downloadName: "서강대-2028-대입전형시행계획.pdf",
  },
  {
    id: "seoul-national-univ",
    region: "seoul",
    regionLabel: "서울",
    university: "서울대",
    file: "/admissions/2028/seoul/seoul-national-univ.pdf",
    downloadName: "서울대-2028-대입전형시행계획.pdf",
  },
  {
    id: "university-of-seoul",
    region: "seoul",
    regionLabel: "서울",
    university: "서울시립대",
    file: "/admissions/2028/seoul/university-of-seoul.pdf",
    downloadName: "서울시립대-2028-대입전형시행계획.pdf",
  },
  {
    id: "sungkyunkwan-univ",
    region: "seoul",
    regionLabel: "서울",
    university: "성균관대",
    file: "/admissions/2028/seoul/sungkyunkwan-univ.pdf",
    downloadName: "성균관대-2028-대입전형시행계획.pdf",
  },
  {
    id: "sookmyung-womens-univ",
    region: "seoul",
    regionLabel: "서울",
    university: "숙명여대",
    file: "/admissions/2028/seoul/sookmyung-womens-univ.pdf",
    downloadName: "숙명여대-2028-대입전형시행계획.pdf",
  },
  {
    id: "yonsei-univ",
    region: "seoul",
    regionLabel: "서울",
    university: "연세대",
    file: "/admissions/2028/seoul/yonsei-univ.pdf",
    downloadName: "연세대-2028-대입전형시행계획.pdf",
  },
  {
    id: "ewha-womans-univ",
    region: "seoul",
    regionLabel: "서울",
    university: "이화여대",
    file: "/admissions/2028/seoul/ewha-womans-univ.pdf",
    downloadName: "이화여대-2028-대입전형시행계획.pdf",
  },
  {
    id: "chung-ang-univ",
    region: "seoul",
    regionLabel: "서울",
    university: "중앙대",
    file: "/admissions/2028/seoul/chung-ang-univ.pdf",
    downloadName: "중앙대-2028-대입전형시행계획.pdf",
  },
  {
    id: "hankuk-univ-foreign-studies",
    region: "seoul",
    regionLabel: "서울",
    university: "한국외대",
    file: "/admissions/2028/seoul/hankuk-univ-foreign-studies.pdf",
    downloadName: "한국외대-2028-대입전형시행계획.pdf",
  },
  {
    id: "hanyang-univ",
    region: "seoul",
    regionLabel: "서울",
    university: "한양대",
    file: "/admissions/2028/seoul/hanyang-univ.pdf",
    downloadName: "한양대-2028-대입전형시행계획.pdf",
  },
  {
    id: "hongik-univ",
    region: "seoul",
    regionLabel: "서울",
    university: "홍익대",
    file: "/admissions/2028/seoul/hongik-univ.pdf",
    downloadName: "홍익대-2028-대입전형시행계획.pdf",
  },
  {
    id: "kyungsung-univ",
    region: "busan",
    regionLabel: "부산",
    university: "경성대",
    file: "/admissions/2028/busan/kyungsung-univ.pdf",
    downloadName: "경성대-2028-대입전형시행계획.pdf",
  },
  {
    id: "kosin-univ",
    region: "busan",
    regionLabel: "부산",
    university: "고신대",
    file: "/admissions/2028/busan/kosin-univ.pdf",
    downloadName: "고신대-2028-대입전형시행계획.pdf",
  },
  {
    id: "tongmyong-univ",
    region: "busan",
    regionLabel: "부산",
    university: "동명대",
    file: "/admissions/2028/busan/tongmyong-univ.pdf",
    downloadName: "동명대-2028-대입전형시행계획.pdf",
  },
  {
    id: "dongseo-univ",
    region: "busan",
    regionLabel: "부산",
    university: "동서대",
    file: "/admissions/2028/busan/dongseo-univ.pdf",
    downloadName: "동서대-2028-대입전형시행계획.pdf",
  },
  {
    id: "donga-univ",
    region: "busan",
    regionLabel: "부산",
    university: "동아대",
    file: "/admissions/2028/busan/donga-univ.pdf",
    downloadName: "동아대-2028-대입전형시행계획.pdf",
  },
  {
    id: "dongeui-univ",
    region: "busan",
    regionLabel: "부산",
    university: "동의대",
    file: "/admissions/2028/busan/dongeui-univ.pdf",
    downloadName: "동의대-2028-대입전형시행계획.pdf",
  },
  {
    id: "pukyong-national-univ",
    region: "busan",
    regionLabel: "부산",
    university: "부경대",
    file: "/admissions/2028/busan/pukyong-national-univ.pdf",
    downloadName: "부경대-2028-대입전형시행계획.pdf",
  },
  {
    id: "busan-national-univ-of-education",
    region: "busan",
    regionLabel: "부산",
    university: "부산교대",
    file: "/admissions/2028/busan/busan-national-univ-of-education.pdf",
    downloadName: "부산교대-2028-대입전형시행계획.pdf",
  },
  {
    id: "pusan-national-univ",
    region: "busan",
    regionLabel: "부산",
    university: "부산대",
    file: "/admissions/2028/busan/pusan-national-univ.pdf",
    downloadName: "부산대-2028-대입전형시행계획.pdf",
  },
  {
    id: "busan-univ-foreign-studies",
    region: "busan",
    regionLabel: "부산",
    university: "부산외대",
    file: "/admissions/2028/busan/busan-univ-foreign-studies.pdf",
    downloadName: "부산외대-2028-대입전형시행계획.pdf",
  },
  {
    id: "silla-univ",
    region: "busan",
    regionLabel: "부산",
    university: "신라대",
    file: "/admissions/2028/busan/silla-univ.pdf",
    downloadName: "신라대-2028-대입전형시행계획.pdf",
  },
  {
    id: "youngsan-univ",
    region: "busan",
    regionLabel: "부산",
    university: "영산대",
    file: "/admissions/2028/busan/youngsan-univ.pdf",
    downloadName: "영산대-2028-대입전형시행계획.pdf",
  },
  {
    id: "inje-univ",
    region: "busan",
    regionLabel: "부산",
    university: "인제대",
    file: "/admissions/2028/busan/inje-univ.pdf",
    downloadName: "인제대-2028-대입전형시행계획.pdf",
  },
  {
    id: "korea-maritime-ocean-univ",
    region: "busan",
    regionLabel: "부산",
    university: "한국해양대",
    file: "/admissions/2028/busan/korea-maritime-ocean-univ.pdf",
    downloadName: "한국해양대-2028-대입전형시행계획.pdf",
  },
];
