import type { CareerResource } from "@/lib/content";

export const staticCareerResources: CareerResource[] = [
  {
    id: -1,
    category: "가이드",
    title: "수시 전형을 읽는 순서",
    summary: "모집요강을 처음 볼 때 전형명보다 먼저 확인해야 할 기준을 정리했습니다.",
    key_points: ["지원 자격과 추천 인원", "전형 요소와 반영 비율", "수능최저학력기준", "전년도와 달라진 점"],
    content: "대학 이름이나 합격선만 보지 말고 지원 자격, 전형 방법, 수능최저, 제출 서류 순서로 확인하세요. 같은 대학이라도 전형별로 요구하는 준비가 크게 다릅니다.",
    link_url: null,
    attachment_url: null,
    attachment_name: null,
    created_at: "2026-06-10T00:00:00.000Z",
  },
  {
    id: -2,
    category: "가이드",
    title: "교과 선택 자료 활용법",
    summary: "희망 모집단위의 핵심과목과 권장과목을 확인하는 방법입니다.",
    key_points: ["관심 학과를 2~3개 비교", "핵심과목 우선 확인", "학교 개설 여부와 이수 가능성 점검"],
    content: "권장과목은 단순히 많이 듣는 것이 목표가 아닙니다. 관심 분야와 연결되는 과목을 선택하고, 수업에서 무엇을 배우고 탐구했는지가 중요합니다.",
    link_url: null,
    attachment_url: null,
    attachment_name: null,
    created_at: "2026-06-09T00:00:00.000Z",
  },
  {
    id: -3,
    category: "용어사전",
    title: "학생부교과전형",
    summary: "학교생활기록부 교과 성적을 중심으로 평가하는 수시 전형입니다.",
    key_points: ["대학별 반영 교과", "학년별·과목별 반영 방식", "수능최저 유무", "학교장 추천 조건"],
    content: "대학마다 반영하는 과목과 등급 환산 방식이 다르므로 단순 평균등급만으로 판단하면 안 됩니다.",
    link_url: null,
    attachment_url: null,
    attachment_name: null,
    created_at: "2026-06-08T00:00:00.000Z",
  },
  {
    id: -4,
    category: "용어사전",
    title: "학생부종합전형",
    summary: "학교생활기록부를 바탕으로 학업역량과 진로역량 등을 종합적으로 평가하는 전형입니다.",
    key_points: ["교과 성취와 선택 과목", "수업 참여와 탐구", "전공 관련 활동의 연결성"],
    content: "활동의 개수보다 수업과 탐구에서 무엇을 배우고 어떻게 성장했는지가 중요합니다.",
    link_url: null,
    attachment_url: null,
    attachment_name: null,
    created_at: "2026-06-07T00:00:00.000Z",
  },
  {
    id: -5,
    category: "용어사전",
    title: "수능최저학력기준",
    summary: "수시 전형에서 합격하기 위해 충족해야 하는 수능 영역별 최소 등급 조건입니다.",
    key_points: ["반영 영역 수", "탐구 반영 방식", "한국사 조건", "응시 필수 영역"],
    content: "학생부 평가나 면접을 통과해도 수능최저를 충족하지 못하면 최종 합격할 수 없습니다.",
    link_url: null,
    attachment_url: null,
    attachment_name: null,
    created_at: "2026-06-06T00:00:00.000Z",
  },
];
