alter table public.notices
  add column if not exists category text not null default '일반',
  add column if not exists due_date date,
  add column if not exists publish_start date,
  add column if not exists publish_end date,
  add column if not exists link_url text,
  add column if not exists attachment_url text,
  add column if not exists attachment_name text;

update public.notices
set category = '중요'
where is_important = true and category = '일반';

create table if not exists public.class_items (
  id bigint generated by default as identity primary key,
  item_type text not null check (item_type in ('시험', '수행평가', '제출', '준비물')),
  title text not null,
  subject text,
  date date not null,
  end_date date,
  scope text,
  preparation text,
  details text,
  link_url text,
  attachment_url text,
  attachment_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.career_resources (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('가이드', '용어사전', '자료')),
  title text not null,
  summary text not null,
  key_points text[] not null default '{}',
  content text,
  link_url text,
  attachment_url text,
  attachment_name text,
  created_at timestamptz not null default now()
);

alter table public.notices enable row level security;
alter table public.class_items enable row level security;
alter table public.career_resources enable row level security;

drop policy if exists "public read notices" on public.notices;
create policy "public read notices" on public.notices for select using (true);
drop policy if exists "public read class items" on public.class_items;
create policy "public read class items" on public.class_items for select using (true);
drop policy if exists "public read career resources" on public.career_resources;
create policy "public read career resources" on public.career_resources for select using (true);

insert into storage.buckets (id, name, public)
values ('class-files', 'class-files', true)
on conflict (id) do update set public = true;

drop policy if exists "public read class files" on storage.objects;
create policy "public read class files"
on storage.objects for select
using (bucket_id = 'class-files');
