create table if not exists public.evening_study_settings (
  id smallint primary key default 1 check (id = 1),
  effective_date date not null default current_date,
  session_8_start time not null default '16:40',
  session_8_end time not null default '17:30',
  session_1_start time not null default '18:30',
  session_1_end time not null default '19:40',
  session_2_start time not null default '19:50',
  session_2_end time not null default '21:00',
  updated_at timestamptz not null default now()
);

create table if not exists public.evening_study_students (
  id bigint generated by default as identity primary key,
  class_number text not null unique,
  masked_name text not null,
  monday text not null default '' check (monday in ('', '8', '1', '2')),
  tuesday text not null default '' check (tuesday in ('', '8', '1', '2')),
  wednesday text not null default '' check (wednesday in ('', '8', '1', '2')),
  thursday text not null default '' check (thursday in ('', '8', '1', '2')),
  friday text not null default '' check (friday in ('', '8', '1', '2')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.evening_study_settings enable row level security;
alter table public.evening_study_students enable row level security;

drop policy if exists "public read evening study settings" on public.evening_study_settings;
create policy "public read evening study settings"
on public.evening_study_settings for select
using (true);

drop policy if exists "public read evening study students" on public.evening_study_students;
create policy "public read evening study students"
on public.evening_study_students for select
using (true);

insert into public.evening_study_settings (
  id,
  effective_date,
  session_8_start,
  session_8_end,
  session_1_start,
  session_1_end,
  session_2_start,
  session_2_end
)
values (1, '2026-08-28', '16:40', '17:30', '18:30', '19:40', '19:50', '21:00')
on conflict (id) do nothing;

insert into public.evening_study_students (
  class_number,
  masked_name,
  monday,
  tuesday,
  wednesday,
  thursday,
  friday
)
values
  ('03', '김*언', '1', '2', '1', '2', '1'),
  ('04', '김*연', '8', '8', '8', '8', '8'),
  ('12', '박*원', '2', '1', '1', '8', '2'),
  ('16', '송*우', '', '2', '', '2', '2'),
  ('18', '이*', '8', '8', '8', '8', '8'),
  ('20', '이*수', '8', '8', '8', '8', '8'),
  ('21', '좌*윤', '8', '8', '8', '8', '8'),
  ('22', '진*랑', '', '2', '', '2', '2')
on conflict (class_number) do nothing;
