create table if not exists public.roadmap_items (
  id bigint generated by default as identity primary key,
  month text not null check (month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  title text not null,
  description text not null,
  action_points text[] not null default '{}',
  link_url text,
  created_at timestamptz not null default now()
);

alter table public.roadmap_items enable row level security;

drop policy if exists "public read roadmap items" on public.roadmap_items;
create policy "public read roadmap items"
on public.roadmap_items for select
using (true);
